### ISSUE TITLE
Problem rebuilding styles.css.

### ISSUE THREAD

**Issue by paulmacp** [TimPietrusky/timpietrusky.com-keystone#15]
Please excuse this potentially naive question. I am trying to regenerate style.css from the sccs files and I am getting nothing but grief. 

    u153:src paulmacp$ ls
    components	core		styles.scss
    u153:src paulmacp$ sass --scss styles.scss styles.css
    Error: File to import not found or unreadable: compass/css3.
           Load path: /Users/paulmacp/Sites/keystone/timpietrusky.com-keystone/public/css/src
            on line 1 of styles.scss
       Use --trace for backtrace.
    u153:src paulmacp$

**Comment by paulmacp** [comment]
Caught my own stupid question ... less not sass.

**Comment by TimPietrusky** [comment]
No problem! :D
